### ISSUE TITLE
Väderdata-uppgift

### ISSUE THREAD

**Issue by gorelhedin** [lunduniversity/schoolprog-satellite#3]
Ett skelett till väderdata-uppgiften finns under `exercises`. Inspiration till uppgiften finns här:

- LU skolprog-repots [skiss](https://github.com/lunduniversity/schoolprog/tree/master/exercises/weatherdata)
- Gamla issues om väderdata-uppgiften i LU skolprog-repot:
    - [weatherdata exercise](https://github.com/lunduniversity/schoolprog/issues/35)
    - [weatherdata repl.it and http](https://github.com/lunduniversity/schoolprog/issues/9)
- [Görels experiment på repl.it](https://repl.it/@gorelhedin/WeatherData)

**Comment by TeodorBucht1729** [comment]
Uppgiften är redo att granskas för feedback. 
Lösningar till uppgifterna finns i uppgiftsbeskrivningen, men även i filerna sol1.py och sol2-5.py.
